AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs8.10
    Environment:
      Variables:
        TABLE_NAME:
          Ref: Contacts
    AutoPublishAlias: live
    DeploymentPreference:
      Type: Canary10Percent5Minutes
  Api:
    Name: ContactsApiSam
    # Uncomment to require API key (example API change)
    # Auth:
    #   ApiKeyRequired: true
Resources:
  Contacts:
    Type: AWS::Serverless::SimpleTable
  CreateContact:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda_code
      Handler: crud.create
      Policies: AmazonDynamoDBFullAccess
      Events:
        Route:
          Type: Api
          Properties:
            Path: /contacts
            Method: POST
  ListContacts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda_code
      Handler: crud.list
      Policies: AmazonDynamoDBFullAccess
      Events:
        Route:
          Type: Api
          Properties:
            Path: /contacts
            Method: GET
  GetContact:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda_code
      Handler: crud.get
      Policies: AmazonDynamoDBFullAccess
      Events:
        Route:
          Type: Api
          Properties:
            Path: /contacts/{id}
            Method: GET
  UpdateContact:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda_code
      Handler: crud.update
      Policies: AmazonDynamoDBFullAccess
      Events:
        Route:
          Type: Api
          Properties:
            Path: /contacts/{id}
            Method: PATCH
  DeleteContact:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda_code
      Handler: crud.delete
      Policies: AmazonDynamoDBFullAccess
      Events:
        Route:
          Type: Api
          Properties:
            Path: /contacts/{id}
            Method: DELETE
