AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs10.x
    Environment:
      Variables:
        TABLE_NAME:
          Ref: Contacts
    AutoPublishAlias: live
    DeploymentPreference:
      Type: Canary10Percent5Minutes
  Api:
    Name: ContactsApiSam
    # Uncomment to require API key (example API change)
    # Auth:
    #   ApiKeyRequired: true
Resources:
  Contacts:
    Type: AWS::Serverless::SimpleTable
  CreateContact:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../crud_code
      Handler: index.create
      Events:
        Route:
          Type: Api
          Properties:
            Path: /contacts
            Method: POST
  ListContacts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../crud_code
      Handler: index.list
      Events:
        Route:
          Type: Api
          Properties:
            Path: /contacts
            Method: GET
            
